### PR TITLE
Added Django 1.9 support.

### PR DESCRIPTION
**Pull request by timgraham**
Addresses https://github.com/jezdez/django-hosts/issues/40.

### CODE REVIEW

**Comment by onekiloparsec** [comment]
It seems the regression in Django is fixed. Any news on this front, then?

**Comment by timgraham** [comment]
Build is failing because coverage dropped support for Python 3.2. We can pin `coverage==3.7.1` or drop support too.

Not sure why the `python3.5` interpreter isn't found. It seems it should be supported per http://docs.travis-ci.com/user/languages/python/.

**Comment by timgraham** [comment]
This should be ready for merge now. Used the technique described in https://github.com/travis-ci/travis-ci/issues/4794 for Python 3.5 support on Travis.

**Comment by akheron** [comment]
Django 1.9 RC is out. Any chance of merging this?

**Comment by thoas** [comment]
Django 1.9 has been released, @timgraham any chance for merging this and releasing a new version on pypi?

**Comment by beaugunderson** [comment]
:thumbsup:

**Pull request merged**
