### PR TITLE
Fix Travis deployment condition

### PR DESCRIPTION
**Pull request by timgraham**
Broken in 2e6e526f3a84c1f8c867f41c0537f4d8c949cf48

(untested, may not work)

### CODE REVIEW

**Comment by timgraham** [comment]
@Djailla, does it look like it might work?

**Comment by Djailla** [comment]
Looks good to me !

**Comment by jezdez** [comment]
Hey folks sorry for the breakage, it would be better to just use build stages for this so no condition is needed. I'll update the branch with the needed change..

**Comment by jezdez** [comment]
@timgraham Let me know if this doesn't works out when you redo the 4.0 tag. Thank you!

**Pull request merged**
