### PR TITLE
better syntax highlighting

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by bashu** [comment]
to @daadu here it is

**Comment by daadu** [comment]
Any reason I am referred?

**Comment by bashu** [comment]
to @daadu I am sorry, I have mistyped @ddabble username 🤦‍♂️

**Comment by bashu** [comment]
to @ddabble here it is

**Review by ddabble — APPROVED** [review]
Excellent! 😄

**Comment by timgraham** [comment]
My experience working with Django's docs is that unnecessary to use `.. code-block:: python` because python is Sphinx's default.

Btw, @ddabble please use squash and merge or rebase and merge to keep Git's history free of merge commits. Thanks.

**Comment by ddabble** [comment]
> My experience working with Django's docs is that unnecessary to use `.. code-block:: python` because python is Sphinx's default.

That's fair, but at least now it's explicit, and it also looks better on GitHub 👌 

> Btw, @ddabble please use squash and merge or rebase and merge to keep Git's history free of merge commits. Thanks.

Alright, thanks for making me aware of that, I'll keep it in mind 😊

**Pull request merged**
